name: Automation Workflow

on:
  push:
    branches:
      - main

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (if Java is required)
        uses: actions/setup-java@v2
        with:
          java-version: 11  # Adjust as needed

      - name: Run automation script
        run: |
          chmod +x scripts/automation_script.sh
          scripts/automation_script.sh
