name: Automation Workflow

on:
  push:
    branches:
      - main

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (if Java is required)
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'  # Specify the distribution you want to use, e.g., adopt, zulu
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Run automation script
        run: |
          chmod +x scripts/automation_script.sh
          scripts/automation_script.sh
